export type CurrencyPair = {
  code: string;
  name: string;
  isCrypto: boolean;
};

const cryptoCodes = ['BTC', 'LTC', 'ETH', 'XRP', 'DOGE', 'SOL', 'BNB', 'BRETT', 'XAU', 'XAG', 'XBR'];

const rawCurrencies: { [key: string]: string } = {
    'USD': 'Dólar Americano',
    'USDT': 'Dólar Americano Turismo',
    'CAD': 'Dólar Canadense',
    'BRL': 'Real Brasileiro',
    'BRLT': 'Real Brasileiro Turismo',
    'EUR': 'Euro',
    'GBP': 'Libra Esterlina',
    'ARS': 'Peso Argentino',
    'BTC': 'Bitcoin',
    'LTC': 'Litecoin',
    'JPY': 'Iene Japonês',
    'CHF': 'Franco Suíço',
    'AUD': 'Dólar Australiano',
    'CNY': 'Yuan Chinês',
    'ILS': 'Novo Shekel Israelense',
    'ETH': 'Ethereum',
    'XRP': 'XRP',
    'DOGE': 'Dogecoin',
    'NZD': 'Dólar Neozelandês',
    'ZAR': 'Rand Sul-Africano',
    'TRY': 'Nova Lira Turca',
    'MXN': 'Peso Mexicano',
    'PLN': 'Zlóti Polonês',
    'SEK': 'Coroa Sueca',
    'SGD': 'Dólar de Cingapura',
    'DKK': 'Coroa Dinamarquesa',
    'NOK': 'Coroa Norueguesa',
    'HUF': 'Florim Húngaro',
    'CZK': 'Coroa Checa',
    'THB': 'Baht Tailandês',
    'AED': 'Dirham dos Emirados',
    'JOD': 'Dinar Jordaniano',
    'KWD': 'Dinar Kuwaitiano',
    'HKD': 'Dólar de Hong Kong',
    'SAR': 'Riyal Saudita',
    'INR': 'Rúpia Indiana',
    'KRW': 'Won Sul-Coreano',
    'FJD': 'Dólar de Fiji',
    'GHS': 'Cedi Ganês',
    'KYD': 'Dólar das Ilhas Cayman',
    'ALL': 'Lek Albanês',
    'AMD': 'Dram Armênio',
    'ANG': 'Guilder das Antilhas',
    'BBD': 'Dólar de Barbados',
    'BDT': 'Taka de Bangladesh',
    'BGN': 'Lev Búlgaro',
    'BHD': 'Dinar do Bahrein',
    'BIF': 'Franco Burundinense',
    'BND': 'Dólar de Brunei',
    'BOB': 'Boliviano',
    'BSD': 'Dólar das Bahamas',
    'BWP': 'Pula de Botswana',
    'BZD': 'Dólar de Belize',
    'CLP': 'Peso Chileno',
    'COP': 'Peso Colombiano',
    'CRC': 'Colón Costarriquenho',
    'CUP': 'Peso Cubano',
    'DJF': 'Franco do Djubouti',
    'DOP': 'Peso Dominicano',
    'DZD': 'Dinar Argelino',
    'EGP': 'Libra Egípcia',
    'ETB': 'Birr Etíope',
    'GEL': 'Lari Georgiano',
    'GMD': 'Dalasi da Gâmbia',
    'GNF': 'Franco de Guiné',
    'GTQ': 'Quetzal Guatemalteco',
    'HNL': 'Lempira Hondurenha',
    'HRK': 'Kuna Croata',
    'HTG': 'Gourde Haitiano',
    'IDR': 'Rupia Indonésia',
    'IQD': 'Dinar Iraquiano',
    'IRR': 'Rial Iraniano',
    'ISK': 'Coroa Islandesa',
    'JMD': 'Dólar Jamaicano',
    'KES': 'Shilling Queniano',
    'KHR': 'Riel Cambojano',
    'KMF': 'Franco Comorense',
    'KZT': 'Tengue Cazaquistanês',
    'LAK': 'Kip Laosiano',
    'LBP': 'Libra Libanesa',
    'LKR': 'Rúpia de Sri Lanka',
    'LSL': 'Loti do Lesoto',
    'LYD': 'Dinar Líbio',
    'MAD': 'Dirham Marroquino',
    'MDL': 'Leu Moldavo',
    'MGA': 'Ariary Madagascarense',
    'MKD': 'Denar Macedônio',
    'MMK': 'Kyat de Mianmar',
    'MOP': 'Pataca de Macau',
    'MRO': 'Ouguiya Mauritana',
    'MUR': 'Rúpia Mauriciana',
    'MVR': 'Rufiyaa Maldiva',
    'MWK': 'Kwacha Malauiana',
    'MYR': 'Ringgit Malaio',
    'NAD': 'Dólar Namíbio',
    'NGN': 'Naira Nigeriana',
    'NIO': 'Córdoba Nicaraguense',
    'NPR': 'Rúpia Nepalesa',
    'OMR': 'Rial Omanense',
    'PAB': 'Balboa Panamenho',
    'PEN': 'Sol do Peru',
    'PGK': 'Kina Papua-Nova Guiné',
    'PHP': 'Peso Filipino',
    'PKR': 'Rúpia Paquistanesa',
    'PYG': 'Guarani Paraguaio',
    'QAR': 'Rial Catarense',
    'RON': 'Leu Romeno',
    'RSD': 'Dinar Sérvio',
    'RWF': 'Franco Ruandês',
    'SCR': 'Rúpias de Seicheles',
    'SDG': 'Libra Sudanesa',
    'SOS': 'Shilling Somaliano',
    'STD': 'Dobra São Tomé/Príncipe',
    'SVC': 'Colon de El Salvador',
    'SYP': 'Libra Síria',
    'SZL': 'Lilangeni Suazilandês',
    'TND': 'Dinar Tunisiano',
    'TTD': 'Dólar de Trinidad',
    'TWD': 'Dólar Taiuanês',
    'TZS': 'Shilling Tanzaniano',
    'UAH': 'Hryvinia Ucraniana',
    'UGX': 'Shilling Ugandês',
    'UYU': 'Peso Uruguaio',
    'UZS': 'Som Uzbequistanês',
    'VEF': 'Bolívar Venezuelano',
    'VND': 'Dong Vietnamita',
    'VUV': 'Vatu de Vanuatu',
    'XAF': 'Franco CFA Central',
    'XCD': 'Dólar do Caribe Oriental',
    'XOF': 'Franco CFA Ocidental',
    'XPF': 'Franco CFP',
    'YER': 'Riyal Iemenita',
    'ZMK': 'Kwacha Zambiana',
    'RUB': 'Rublo Russo',
    'BYN': 'Rublo Bielorrusso',
    'MZN': 'Metical de Moçambique',
    'AZN': 'Manat Azeri',
    'CNH': 'Yuan chinês offshore',
    'KGS': 'Som Quirguistanês',
    'TJS': 'Somoni do Tajiquistão',
    'AOA': 'Kwanza Angolano',
    'XBR': 'Brent Spot',
    'TMT': 'TMT',
    'XAGG': 'Prata',
    'MNT': 'Mongolian Tugrik',
    'AFN': 'Afghani do Afeganistão',
    'NGNI': 'Naira Nigeriana',
    'ZWL': 'Dólar Zimbabuense',
    'BBD': 'Dólar de Barbados',
    'BAM': 'Marco Conversível',
    'CVE': 'Escudo cabo-verdiano',
    'SDR': 'DSE',
    'XAU': 'Ouro',
    'BRLPTAX': 'Real Brasileiro PTAX',
    'BRETT': 'Brett',
    'SOL': 'Solana',
    'BNB': 'Binance Coin',
};

const uniqueCurrencyCodes = [...new Set(Object.keys(rawCurrencies))];

export const currencies: CurrencyPair[] = uniqueCurrencyCodes.map(code => ({
    code: code,
    name: rawCurrencies[code] || code,
    isCrypto: cryptoCodes.includes(code)
}));
